In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.random.randint(0,10, size=10)

array([2, 9, 2, 2, 6, 7, 2, 9, 8, 6])

In [8]:
np.random.normal(10,4, (3,4))
#Ortalaması 10, standart sapması 4 ve 3'e 4'lük bir normal dağılan matris oluşturduk.

array([[ 8.25042386,  8.47163382, 11.93023412,  8.45217921],
       [16.77580303, 14.10208251,  6.87425472,  9.5755996 ],
       [21.10317443,  6.35126455,  0.67933455, 12.3975171 ]])

## Numpy Array Özellikleri

### ndim: boyut sayısı
### shape: boyut bilgisi
### size: toplam eleman sayısı
### dtype: array veri tipi

In [9]:
a = np.random.randint(0,10, size=5)

In [10]:
a

array([7, 9, 0, 5, 3])

In [11]:
a.ndim

1

In [12]:
a.shape

(5,)

In [13]:
a.size

5

In [14]:
a.dtype

dtype('int32')

## Yeniden Şekillendirme(Reshaping)

In [16]:
ar = np.random.randint(1,10, size=9).reshape(3,3)

In [17]:
ar

array([[9, 3, 4],
       [1, 3, 5],
       [8, 1, 9]])

## Index Seçimi

In [18]:
a = np.random.randint(10, size=10)

In [19]:
a[0]

2

In [20]:
a[0:5]

array([2, 5, 5, 6, 2])

In [21]:
a[0] = 999

In [22]:
a

array([999,   5,   5,   6,   2,   1,   7,   0,   9,   5])

In [23]:
m = np.random.randint(10, size=(3,5))

In [24]:
m[0,0]

7

In [25]:
m[1,1]

9

In [26]:
m

array([[7, 2, 5, 6, 0],
       [0, 9, 9, 3, 1],
       [7, 5, 2, 7, 7]])

In [27]:
m[2,3]

7

In [28]:
m[2,3] = 999

In [29]:
m

array([[  7,   2,   5,   6,   0],
       [  0,   9,   9,   3,   1],
       [  7,   5,   2, 999,   7]])

In [30]:
m[:, 0]

array([7, 0, 7])

In [31]:
m[1,:]

array([0, 9, 9, 3, 1])

In [32]:
m[0:2, 0:3]

array([[7, 2, 5],
       [0, 9, 9]])

## Fancy Index

In [43]:
v = np.arange(0, 30, 3)
# 0' dan 30'a kadar 3'er 3'er artacak

In [44]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
v[1]

3

In [46]:
v[4]

12

In [47]:
catch = [1,2,3]

In [48]:
v[catch]

array([3, 6, 9])

## Numpy'da Koşullu İşlemler

In [49]:
#Klasik Döngü ile
ab = []
for i in v:
    if i <3:
        ab.append(i)

In [50]:
ab

[0]

In [41]:
# Numpy İle

In [42]:
v[v<3]

array([0])

In [51]:
v[v>3]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
v[v!=3]

array([ 0,  6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
v[v==3]

array([3])

## Matematiksel İşlemler

In [54]:
v = np.array([1,2,3,4,5])

In [55]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [56]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [57]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [58]:
np.subtract(v, 1)
#çıkarma işlemi

array([0, 1, 2, 3, 4])

In [59]:
np.add(v, 1)
#toplama işlemi

array([2, 3, 4, 5, 6])

In [60]:
np.mean(v)
#ortalama alma işlemi

3.0

In [61]:
np.sum(v)
#sayıların toplamını alma işlemi

15

In [63]:
np.min(v)
#minimum değer alma işlemi

1

In [64]:
np.max(v)
#maximum değer alma işlemi

5

In [65]:
np.var(v)
#varyans alma işlemi

2.0

In [66]:
# Numpy ile İki Bilinmeyenli Denklem Çözümü

In [67]:
# 5x0 +x1 = 12
# x0 + 3x1 = 10

In [68]:
a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

In [69]:
np.linalg.solve(a, b)

array([1.85714286, 2.71428571])